### ISSUE TITLE
Contributions welcome?

### ISSUE THREAD

**Issue by benninkrs** [Jutho/TupleTools.jl#13]
@Jutho A few months ago, being unaware of TupleTools, I wrote a small (unregistered) package that adds capabilities for working with tuples in a fast and convenient way.  While there is some overlap with TupleTools, I think my package provides some functionality that complements TupleTools nicely and it would make sense to assimilate some of it into this established package.  Would you be open to a PR?

**Comment by Jutho** [comment]
I think so yes, is there anywhere that I could view the code you have? Or just prepare a PR indeed :-).

I have to say that I have become less dependent of TupleTools.jl since Julia 1.0 (or more recent?) as tuples gained better (i.e. faster, more type stable) support in broadcasting. So this package has not gotten a lot of attention lately, although it is still being used in my codebase and I think everything is still working like it should.

**Comment by benninkrs** [comment]
I think the best way to show you the code is just to submit the PR :)

I have found that the functions I have written are significantly faster than those in Base in some cases, especially for tuples of length > 10.  For the longer tuples, I have found that using a temporary `MVector` is often the most performant approach.  (Incidentally, I wrote my tuple package for working with tensor indices (I wrote a package that uses your `TensorOperations`).  For small tensors, the index mangling turned out to make a significant contribution to the run time.)

A couple comments:
- For indexing a tuple by a tuple, why did you call it `getindices` instead of overloading `getindex`?
- For sorting, I used quicksort whereas you seem to use a merge sort.  It would be interesting to see which is faster.

**Comment by Jutho** [comment]
> A couple questions:
> 
> Why don't you export any of the new functions?
> For indexing a tuple by a tuple, why did you name it getindices instead of overloading getindex?
> Did you intentionally define a new vcat instead of importing Base.vcat?

I think these are related questions, so let me answer them in one go. The important thing is that I define functionality for tuples (which are not new types of objects defined in this package), and which is often literally the functionality in `Base`, or additions to it.

So I cannot extend/overload the methods from `Base` as that would count as type piracy. Anything which is not one of the following:
* Defining a new function for types that exist in `Base` or in other packages
* Extending/overloading an existing function for arguments of which at least one is a new type defined in your package

counts as type piracy. So I choose to have internal methods to `TupleTools`, with the same name as the ones in `Base` for which they define alternative implementations, or extended functionality, and which are not exported (as they would then lead to dispatch conflicts). You always have to be explicit in specifying that you want to use the function/implementation from TupleTools, instead of the one from `Base`, by putting `TupleTools.` in front of them.

So yes I intentionally defined new `vcat`, `cumsum`, `sort`, `sum`, `diff`, ...

Regarding `getindices`; this is a new function without a counterpart in `Base`. So I could have exported it, but why would I, if all the other functions that you want to use from this package should still be preceeded by `TupleTools.`

Why did I not name the functionality of `getindices` (which I would now write as `getindices(A, t::Tuple) = getindex.(Ref(A), t)`) as `TupleTools.getindex`. I think that would have been confusing, I tried to make the functions which have the same name as in `Base` have exactly the same functionality.

**Comment by benninkrs** [comment]
> So I cannot extend/overload the methods from Base as that would count as type piracy. 

Ah yes.  Well, my perspective is that the purpose of a package like this is to effectively extend `Base`, so type piracy is kind of the point. Since the new methods do not change functionality but rather add functionality where there previously was none, it doesn't seem like there would be much danger.  But I respect your position.

**Comment by Jutho** [comment]
Yes, in retrospect, my claim that methods with the same name have the same functionality does not hold for `vcat`, as the return type is different. I should probably have called that one `tuplecat`. Anyway, I still think avoiding type piracy is a good target, and I find it perfectly ok to explicitly state `TupleTools.method` in the code where I am using this.
