### ISSUE TITLE
clarification requested

### ISSUE THREAD

**Issue by JeffreySarnoff** [Jutho/TupleTools.jl#16]
Does this comment mean that the tuple of indices at which to delete 
must be given sorted from the largest index to the smallest
in order to obtain the expected behavior?
Do you have a counter example where something is computed incorrectly?

```
@inline _deleteat(t::Tuple, I::Tuple{Int,Int,Vararg{Int}}) =
    _deleteat(_deleteat(t, I[1]), tail(I)) # assumes sorted from big to small
```

**Comment by Jutho** [comment]
I am not sure I understand the question. `_deleteat` with underscore is an internal method, it is called by `deleteat` which makes sure the argument is indeed sorted in reverse order, so that the user does not need to worry about this.

But yes, if you do call `_deleteat` directly with arguments in wrong order, it will be incorrect. If you call `_deleteat(t, (1,2))`, it will first delete the first element of `t`, and then the second element of what remains, which is not the second element of `t` but actually the third.

**Comment by JeffreySarnoff** [comment]
thank you
